In [ ]:
import numpy as np

a= np.array([0,1,2])
print(type(a))

print(a.shape)
print(a[0])
print(a[1])
print(a[2])
a[0]=5
print(a)


<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [ ]:
import numpy as np
b= np.array([[0,1,2],[3,4,5]])
print(b.shape)
print(b)
print(b[0,0],b[0,1],b[1,0])


(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [ ]:
import numpy as np

a = np.zeros((3,3))
print(a)

b = np.ones((2,2))
print(b)

c = np.full((3,3), 7)
print(c)

d = np.random.random((3,3))
print(d)

e = np.eye(3)
print(e)

f = np.array([2, 3, 1, 0])
print(f)

g = np.arange(20)
print(g)

h = np.array([[0, 1,2.0],[0,0,0],(1+1j,3.,2.)])
print(h)

i = np.arange(1, 8, dtype=float) # Fixed: Changed np.float to float
print(i)

j = np.linspace(2, 4, 5)
print(j)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.62739813 0.93844289 0.93863101]
 [0.25811872 0.26136229 0.19028419]
 [0.53525821 0.01659252 0.91256966]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[2 3 1 0]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[0.+0.j 1.+0.j 2.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [1.+1.j 3.+0.j 2.+0.j]]
[1. 2. 3. 4. 5. 6. 7.]
[2.  2.5 3.  3.5 4. ]


In [ ]:
import numpy as np
x= np.array([0,1])
y= np.array([2.0,3.0])

z=np.array([5,6],dtype=np.int64)
print(x.dtype,y.dtype,z.dtype)

int64 float64 int64


In [ ]:
import numpy as np
arr = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])

t=arr[:2,::2]
print("this is the sliced array",t)
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate columns(0 and 2):\n", temp)
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),(3, 0):\n", temp)
cond = arr > 0
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

this is the sliced array [[-1.  0.]
 [ 4.  6.]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]


In [ ]:

import numpy as np
arr = np.array([[1, 5, 6],
[4, 7, 2],
[3, 1, 9]])
print ("Largest element is:", arr.max())
print ("Row-wise maximum elements:",arr.max(axis = 1))
print ("Column-wise minimum elements:",arr.min(axis = 0))
print ("Sum of all array elements:",arr.sum())
print ("Cumulative sum along each row:\n",arr.cumsum(axis = 1))

Largest element is: 9
Row-wise maximum elements: [6 7 9]
Column-wise minimum elements: [1 1 2]
Sum of all array elements: 38
Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[4,3],[2,1]])

print(a+b)
print(a*b)
print(a.dot(b))

[[5 5]
 [5 5]]
[[4 6]
 [6 4]]
[[ 8  5]
 [20 13]]


In [ ]:
import numpy as np
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [ ]:
import numpy as np
arr = np.array([[-1, 2, 0, 4],
[4, -0.5, 6, 0],
[2.6, 0, 7, 8],
[3, -7, 4, 2.0]])
inverse = np.linalg.inv(arr)
inverse

array([[ 4.05707196,  1.98511166, -2.28287841,  1.01736973],
       [ 0.50620347,  0.30272953, -0.24813896, -0.01985112],
       [-2.66253102, -1.13151365,  1.50124069, -0.67990074],
       [ 1.01116625,  0.34491315, -0.44665012,  0.26426799]])

In [ ]:
import numpy as np

# Sample arrays for demonstration
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.array([1, 2])
d = np.array([3, 4])
e = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
f = np.array([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])

print("Dot product of a and b:\n", np.dot(a, b))
print("\nMulti-dot product of a, b, and a:\n", np.linalg.multi_dot([a, b, a]))
print("\nDot product of vectors c and d:\n", np.vdot(c, d))
print("\nInner product of a and b:\n", np.inner(a, b))
print("\nOuter product of c and d:\n", np.outer(c, d))
print("\nMatrix product of a and b:\n", np.matmul(a, b))
print("\nTensor dot product of e and f along specified axes:\n", np.tensordot(e, f, axes=([1, 0], [0, 1])))
print("\nEinstein summation (example - matrix multiplication a * b):\n", np.einsum('ij,jk->ik', a, b))

g = np.array([[1, 2], [3, 4]])
print("\nMatrix g raised to the power of 2:\n", np.linalg.matrix_power(g, 2))


h = np.array([[3, 1], [2, 2]])
eigenvalues, eigenvectors = np.linalg.eig(h)
print("\nEigenvalues of matrix h:", eigenvalues)
print("Right eigenvectors of matrix h:\n", eigenvectors)

symmetric_matrix = np.array([[1, 2], [2, 3]])
symmetric_eigenvalues, symmetric_eigenvectors = np.linalg.eigh(symmetric_matrix)
print("\nEigenvalues of symmetric matrix:\n", symmetric_eigenvalues)
print("Eigenvectors of symmetric matrix:\n", symmetric_eigenvectors)

general_matrix = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
general_eigenvalues = np.linalg.eigvals(general_matrix)
print("\nEigenvalues of general matrix:\n", general_eigenvalues)

Dot product of a and b:
 [[19 22]
 [43 50]]

Multi-dot product of a, b, and a:
 [[ 85 126]
 [193 286]]

Dot product of vectors c and d:
 11

Inner product of a and b:
 [[17 23]
 [39 53]]

Outer product of c and d:
 [[3 4]
 [6 8]]

Matrix product of a and b:
 [[19 22]
 [43 50]]

Tensor dot product of e and f along specified axes:
 [[208 224]
 [256 276]]

Einstein summation (example - matrix multiplication a * b):
 [[19 22]
 [43 50]]

Matrix g raised to the power of 2:
 [[ 7 10]
 [15 22]]

Eigenvalues of matrix h: [4. 1.]
Right eigenvectors of matrix h:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

Eigenvalues of symmetric matrix:
 [-0.23606798  4.23606798]
Eigenvectors of symmetric matrix:
 [[-0.85065081  0.52573111]
 [ 0.52573111  0.85065081]]

Eigenvalues of general matrix:
 [ 6.00000000e+00  6.64845085e-16 -1.84983396e-16]


from now on the dataset part will begin


In [ ]:
import numpy as np


In [ ]:
import pandas as pd

file_path = ''
data=np.loadtxt("/content/sample_data/fitness.txt",dtype="str")
data[:44]

/tmp/ipython-input-1983445970.py:4: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data=np.loadtxt("/content/sample_data/fitness.txt",dtype="str")


array([['06-10-2017', '5464', '200', '181', '5', '0', '66'],
       ['07-10-2017', '6041', '100', '197', '8', '0', '66'],
       ['08-10-2017', '25', '100', '0', '5', '0', '66'],
       ['09-10-2017', '5461', '100', '174', '4', '0', '66'],
       ['10-10-2017', '6915', '200', '223', '5', '500', '66'],
       ['11-10-2017', '4545', '100', '149', '6', '0', '66'],
       ['12-10-2017', '4340', '100', '140', '6', '0', '66'],
       ['13-10-2017', '1230', '100', '38', '7', '0', '66'],
       ['14-10-2017', '61', '100', '1', '5', '0', '66'],
       ['15-10-2017', '1258', '100', '40', '6', '0', '65'],
       ['16-10-2017', '3148', '100', '101', '8', '0', '65'],
       ['17-10-2017', '4687', '100', '152', '5', '0', '65'],
       ['18-10-2017', '4732', '300', '150', '6', '500', '65'],
       ['19-10-2017', '3519', '100', '113', '7', '0', '65'],
       ['20-10-2017', '1580', '100', '49', '5', '0', '65'],
       ['21-10-2017', '2822', '100', '86', '6', '0', '65'],
       ['22-10-2017', '181', '10

In [ ]:
data.shape

(96, 7)

In [ ]:
data[0]

array(['06-10-2017', '5464', '200', '181', '5', '0', '66'], dtype='<U10')

In [ ]:

data.T


array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [ ]:
data1=np.array([[1,2,3]])
print(data1)


[[1 2 3]]
